name: CICD complet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  dependances_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installation dependances
      run: python -m pip install -r requirements.txt
      
    - name: Tests
      run: pytest test_app.py && echo $testok
      env:
        testok: ${{ job.status }}
        
   # - name: echo testok
    #  run: echo $testok

  build_and_login:  
    runs-on: ubuntu-latest
    needs: dependances_and_test #s'execute ssi le job precedent est successfull
    steps:
      - uses: actions/checkout@v3
      - name: Login repo 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build the Docker image
        #if: ${{ job.dependances_and_test.steps.Tests.env.testok == 'true' }}
        run: |
            docker build . --tag mywebapp:latest
            docker tag mywebapp:latest ${{ secrets.DOCKER_USERNAME }}/mywebapp:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/mywebapp:latest
      
    

