name: CICD complet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Installation dependances
      run: python -m pip install -r requirements.txt
    
    - name: Tests
    - uses: actions/python-action@v2
      with:
        working-directory: TP_webapp_python
        entrypoint: pytest tests_app.py
        
    - name: Login repo 
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag mywebapp:$(date +%s)
          docker tag mywebapp:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/mywebapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mywebapp:latest
      
    

