name: CICD complet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  dependances:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installation dependances
      run: python -m pip install -r requirements.txt
      
  #tests:
    #runs-on: ubuntu-latest
    #steps:
    - name: Tests
      run: pytest test_app.py
      env:
        testok: ${{ job.status == 'success' }}
    - name: echo testok
      run: echo $testok

  build_and_login:  
    runs-on: ubuntu-latest
    steps:
      - name: Login repo 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build the Docker image
        if: ${{ job.tests.steps.Tests.env.testok == 'success' }}
        run: |
            docker build . --file Dockerfile --tag mywebapp:latest
            docker tag mywebapp:latest ${{ secrets.DOCKER_USERNAME }}/mywebapp:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/mywebapp:latest
      
    

